name: starter_codes
description: "A new Flutter project."
publish_to: "none"
version: 2.0.0+16

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  another_flushbar: ^1.12.30
  pin_code_fields: ^8.0.1
  dio: ^5.4.3+1
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  url_launcher: ^6.3.0
  get_it: ^7.7.0
  mime: ^1.0.5
  qr_flutter: ^4.1.0
  smooth_page_indicator: ^1.2.1
  file_picker: ^10.1.9
  image_picker: ^1.1.2
  sliding_switch: ^1.1.0
  sliding_sheet2: ^2.0.1
  flutter_animate: ^4.5.2
  google_maps_flutter: ^2.10.1
  dotenv: ^4.2.0
  flutter_dotenv: ^5.2.1
  geocoding: ^4.0.0
  geolocator: ^14.0.1
  flutter_polyline_points: ^2.1.0
  webview_flutter: ^4.13.0
  cached_network_image: ^3.4.1
  equatable: ^2.0.7
  uuid: ^4.5.1
  firebase_messaging: ^15.2.9
  flutter_local_notifications: ^19.3.0
  firebase_core: ^3.15.1
  flutter_launcher_icons: ^0.14.1
  jwt_decoder: ^2.0.1
  location: ^8.0.1
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  flutter_secure_storage: ^9.2.4
  crypto: ^3.0.6
  google_fonts: ^6.2.1
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/tags/
    - .env

flutter_icons:
  image_path: "flutter_launcher_icons.yaml"
